### ISSUE TITLE
GLOS Timestamp Format

### ISSUE THREAD

**Issue by jacobgqc** [glos/IoH2O#1]
From the time field's metadata:
units: seconds since 2001-1-1 0:0:0

For converting to Unix Epoch timestamp, is this value in UTC?

**Comment by tslawecki** [comment]
I wasn't sure, so I went and converted the latest reported time

  5.258826E8 seconds / 60 seconds/minute / 60 minutes/hour / 24 hours/day = 6086.6 days 

The fractional part of 0.6 day puts the observation at 2:30 PM today - several hours in the future - so it's clearly UTC!
